FROM satyajitghana/pytorch:2.3.1

WORKDIR /workspace

# Install any missing dependencies
RUN pip install --no-cache-dir matplotlib

# Copy the model and training code
COPY model.py /workspace/
COPY model-train/train.py /workspace/
COPY model-train/check_train.py /workspace/

CMD ["python", "train.py"] 