version: '3.8'

services:
  base:
    build:
      context: .
      dockerfile: docker/base.Dockerfile
    image: dog-breed-base:latest

  train:
    build:
      context: .
      dockerfile: docker/train.Dockerfile
    depends_on:
      - base
    volumes:
      - ./data:/app/data
      - ./checkpoints:/app/checkpoints
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  eval:
    build:
      context: .
      dockerfile: docker/eval.Dockerfile
    depends_on:
      - base
    volumes:
      - ./data:/app/data
      - ./checkpoints:/app/checkpoints
      - ./predictions:/app/predictions
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  infer:
    build:
      context: .
      dockerfile: docker/infer.Dockerfile
    depends_on:
      - base
    volumes:
      - ./input_images:/app/input
      - ./checkpoints:/app/checkpoints
      - ./predictions:/app/predictions
    ports:
      - "8000:8000"  # For potential web interface
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    depends_on:
      - base
    ports:
      - "8080:8080"
    volumes:
      - ./checkpoints:/app/checkpoints
      - ./predictions:/app/predictions
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
